set_property IOSTANDARD LVCMOS33 [get_ports {light[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {st_light[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wt_light[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {p1}]
# set_property IOSTANDARD LVCMOS33 [get_ports {p3}]
# set_property IOSTANDARD LVCMOS33 [get_ports {p2}]
# set_property IOSTANDARD LVCMOS33 [get_ports {sign}]
set_property IOSTANDARD LVCMOS33 [get_ports {ena[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ena[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ena[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ena[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
# set_property IOSTANDARD LVCMOS33 [get_ports {ri_bt}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {on}]
set_property PACKAGE_PIN D4 [get_ports {light[7]}]
set_property PACKAGE_PIN E3 [get_ports {light[6]}]
set_property PACKAGE_PIN D3 [get_ports {light[5]}]
set_property PACKAGE_PIN F4 [get_ports {light[4]}]
set_property PACKAGE_PIN F3 [get_ports {light[3]}]
set_property PACKAGE_PIN E2 [get_ports {light[2]}]
set_property PACKAGE_PIN D2 [get_ports {light[1]}]
set_property PACKAGE_PIN H2 [get_ports {light[0]}]
set_property PACKAGE_PIN G1 [get_ports {ena[3]}]
set_property PACKAGE_PIN F1 [get_ports {ena[2]}]
set_property PACKAGE_PIN E1 [get_ports {ena[1]}]
set_property PACKAGE_PIN G6 [get_ports {ena[0]}]
set_property PACKAGE_PIN F6 [get_ports {st_light[0]}]
set_property PACKAGE_PIN G4 [get_ports {st_light[1]}]
set_property PACKAGE_PIN G3 [get_ports {st_light[2]}]
set_property PACKAGE_PIN J4 [get_ports {st_light[3]}]
set_property PACKAGE_PIN H4 [get_ports {st_light[4]}]
set_property PACKAGE_PIN J3 [get_ports {st_light[5]}]
set_property PACKAGE_PIN J2 [get_ports {st_light[6]}]
set_property PACKAGE_PIN K2 [get_ports {st_light[7]}]
set_property PACKAGE_PIN K1 [get_ports {wt_light[0]}]
set_property PACKAGE_PIN H6 [get_ports {wt_light[1]}]
set_property PACKAGE_PIN H5 [get_ports {wt_light[2]}]
set_property PACKAGE_PIN J5 [get_ports {wt_light[3]}]
set_property PACKAGE_PIN K6 [get_ports {wt_light[4]}]
set_property PACKAGE_PIN L1 [get_ports {wt_light[5]}]
set_property PACKAGE_PIN M1 [get_ports {wt_light[6]}]
set_property PACKAGE_PIN K3 [get_ports {wt_light[7]}]
set_property PACKAGE_PIN R15 [get_ports {bt}]
set_property PACKAGE_PIN P17 [get_ports {clk}]
# set_property PACKAGE_PIN R1 [get_ports {p1}]
# set_property PACKAGE_PIN N4 [get_ports {p2}]
# set_property PACKAGE_PIN M4 [get_ports {p3}]
# set_property PACKAGE_PIN R2 [get_ports {sign}]
# set_property PACKAGE_PIN R11 [get_ports {ri_bt}]
set_property PACKAGE_PIN P15 [get_ports {rst}]
set_property PACKAGE_PIN R1 [get_ports {on}]